spring:
   data:
       mongodb:
           uri: mongodb://localhost/places
      
teste:
   de:
      profile: usando_default
           
---

spring: 
   profiles: dev
   
teste:
   de:
      profile: em_dev
      
---

spring: 
   profiles: prod
   
teste:
   de:
      profile: em_prod