spring:
  profiles:
    active: development
dynamodb:
  credentials:
    profile: 9c-dev
    region: eu-west-1
  tables:
    user: dev-user
    course: dev-course
    subscription: dev-subscription

---

spring:
  profiles:
    active: test
