spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: akka
    password: topsecret
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update