spring:
  datasource:
    username: postgres
    password: 123456
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: services
    port: 6379
  cache:
    type: redis
endpoints:
  flyway:
    web:
      enabled: true
---
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://services:5432/anotherapplication_test
  jpa:
    hibernate:
      ddl-auto: validate
  cache:
    type: none
endpoints:
  enabled: false # Disable actuator
  flyway:
    web:
      enabled: true

---
spring:
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://services:5432/anotherapplication
  jpa:
    hibernate:
      ddl-auto: validate